### ISSUE TITLE
Use DNS discovery of raft peers

### ISSUE THREAD

**Issue by misterbisson** [autopilotpattern/consul#14]
This implementation depends on orchestration via [`start.sh`](https://github.com/autopilotpattern/consul/blob/master/start.sh) that starts one Consul instance, gets its IP, then starts the remaining Consul instances. That external orchestration is incompatible with the Autopilot Pattern, though this is, admittedly, a special case.

I believe this can be fixed with [DNS-based discovery](https://www.joyent.com/blog/introducing-triton-container-name-service) of raft peers and a `preStart` script that digs for raft members to join with.

**Comment by mterron** [comment]
Using `consul agent -server -config-dir=/config -retry-join consul.svc.<account uuid>.<data center name>.triton.zone` should neatly solve this. This will make the solution Triton specific though.

**Comment by misterbisson** [comment]
> This will make the solution Triton specific though

I'm very concerned about doing anything that would limit the portability of the pattern or any specific implementation, so I take that to heart. I'm suggesting DNS discovery of raft peers, however, because Triton, Mantl, DC/OS, Docker, and Kubernetes all now offer scheduler-backed DNS. Generic Mesos implementations can get it via a number of solutions as well.

I'm probably not thinking of the use cases you have in mind, though. Care to share more?

**Comment by misterbisson** [comment]
Aside: I would not recommend [DNS or infrastructure-backed, passive discovery](http://containersummit.io/articles/active-vs-passive-discovery) except in a limited number of circumstances:
1. This case: peer discovery for Consul, where no more active solution is available
2. Discovery of the Consul service

**Comment by mterron** [comment]
You are right, I could rephrase that to -retry-join $CONSUL_DNS
We could pass the DNS name as an environment variable and that way it'd work for any of the solutions you mentioned.

Agree that this is only valid for initial bootstrapping of the Consul cluster and that is exactly what my example does. A node boots up and tries to join a cluster but instead of using a fixed IP orchestrated by start.sh, it just tries to read a DNS name associated with the consul cluster.

I didn't thought about it because I'm working on a SDC specific solution, sorry.

**Comment by tgross** [comment]
Done in https://github.com/autopilotpattern/consul/pull/19
