### ISSUE TITLE
test failing (maybe post 0.7 upgrade?)

### ISSUE THREAD

**Issue by jacobloveless** [autopilotpattern/consul#27]
Error from /test/node ./raft-test.js

Using Joyent us-east2 as docker host.
`
{ Error: (HTTP code 500) server error - invalid filters: Error: invalid filter "0" - expected an array or object, got: "{\"label\":[\"com.docker.compose.service=consul\"]}" (XXXXXXX-XXXX-XXXXX-XX)
    at /apconsul/test/node_modules/docker-modem/lib/modem.js:229:17
    at getCause (/apconsuledgemesh-deployment/test/node_modules/docker-modem/lib/modem.js:259:7)
    at Modem.buildPayload (/apconsul/test/node_modules/docker-modem/lib/modem.js:228:5)
    at IncomingMessage.<anonymous> (/apconsul/test/node_modules/docker-modem/lib/modem.js:204:14)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  reason: 'server error',
  statusCode: 500,
  json: 'invalid filters: Error: invalid filter "0" - expected an array or object, got: "{\\"label\\":[\\"com.docker.compose.service=consul\\"]}" (XXXXXXX-XXXX-XXXXX-XX)' }
`

**Comment by tgross** [comment]
@jacobloveless the test rig got created in https://github.com/autopilotpattern/consul/pull/3 but we significantly changed out the bootstrap process in https://github.com/autopilotpattern/consul/pull/19. Because we don't have a good way to run CI on this (although CI/testing for Autopilot Pattern blueprints is actually my current primary focus), we haven't been keeping this test rig up to date. (Which, yeah, that's awful. 😦 )

Our current thoughts on the test process can be found in https://github.com/autopilotpattern/testing with examples in use in our [MySQL](https://github.com/autopilotpattern/mysql) and [workshop](https://github.com/autopilotpattern/workshop) blueprints. I'll be reworking the test rig in that light probably right after I wrap up the work I'm currently doing on [vault](https://github.com/autopilotpattern/vault/pull/1). 

I'm going to mark this as a bug and follow up with it in the next couple weeks. PRs welcome in the meantime if you have time!

**Comment by tgross** [comment]
ref https://github.com/autopilotpattern/consul/pull/28

**Comment by tgross** [comment]
The tests have been fixed (totally rewritten, actually) in https://github.com/autopilotpattern/consul/pull/34
